package com.github.snoblind.winterface;

import java.io.IOException;
import java.util.List;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

public interface Window extends EventTarget, GlobalEventHandlers, WindowEventHandlers {
	ApplicationCache getApplicationCache();
	BarProp getLocationbar();
	BarProp getMenubar();
	BarProp getPersonalbar();
	BarProp getScrollbars();
	BarProp getStatusbar();
	BarProp getToolbar();
	boolean isClosed();
	boolean confirm(String message);
	Document getDocument();
	String getDefaultStatus();
	String getName();
	String getStatus();
	String prompt(String message, String defaultText);
	Element getFrameElement();
	External getExternal();
	History getHistory();
	int getInnerWidth();
	int getInnerHeight();
	int getOuterWidth();
	int getOuterHeight();
	List<Window> getFrames();
	Location getLocation();
	long getLength();
	Navigator getNavigator();
	Object eval(String script);
	Object get(String name);
	Object showModalDialog(String url, Object optionalArgument);
	void alert(String message);
	void blur();
	void close();
	void focus();
	void print();
	void setName(String name);
	void setOpener(Window opener);
	void setStatus(String status);
	void stop();
	Window get(long index);
	Window getOpener();
	Window getParent();
	Window getSelf();
	Window getTop();
	Window getWindow();
	Window open(String url, String target, String features, boolean replace) throws IOException;
}